import { useEffect, useState } from 'react';
import {
  AlertTriangle, XCircle, Info, ChevronDown, ChevronRight,
  Loader2, RefreshCw, Eye, EyeOff, FileText, TrendingUp, Download,
} from 'lucide-react';
import type { Engagement, Finding } from '../../lib/apiClient';
import { findingsApi } from '../../lib/apiClient';

const BACKEND_URL = (import.meta.env.VITE_API_URL as string | undefined) ?? '';

interface Props {
  engagement: Engagement;
}

const SEVERITY_CONFIG = {
  critical: {
    icon: XCircle,
    color: 'text-red-400',
    border: 'border-red-500/30',
    bg: 'bg-red-500/8',
    badge: 'bg-red-500/15 border-red-500/30 text-red-400',
    label: 'CRITICAL',
  },
  warning: {
    icon: AlertTriangle,
    color: 'text-amber-400',
    border: 'border-amber-500/30',
    bg: 'bg-amber-500/8',
    badge: 'bg-amber-500/15 border-amber-500/30 text-amber-400',
    label: 'WARNING',
  },
  info: {
    icon: Info,
    color: 'text-blue-400',
    border: 'border-blue-500/30',
    bg: 'bg-blue-500/8',
    badge: 'bg-blue-500/15 border-blue-500/30 text-blue-400',
    label: 'INFO',
  },
} as const;

type SevKey = keyof typeof SEVERITY_CONFIG;

const REC_CONFIG: Record<string, { color: string; border: string; bg: string; label: string }> = {
  proceed: { color: 'text-green-400', border: 'border-green-500/40', bg: 'bg-green-500/10', label: 'PROCEED' },
  proceed_with_caution: { color: 'text-amber-400', border: 'border-amber-500/40', bg: 'bg-amber-500/10', label: 'PROCEED WITH CAUTION' },
  caution: { color: 'text-amber-400', border: 'border-amber-500/40', bg: 'bg-amber-500/10', label: 'CAUTION' },
  do_not_proceed: { color: 'text-red-400', border: 'border-red-500/40', bg: 'bg-red-500/10', label: 'DO NOT PROCEED' },
  reject: { color: 'text-red-400', border: 'border-red-500/40', bg: 'bg-red-500/10', label: 'REJECT' },
};

function ExecutiveSummaryCard({ finding }: { finding: Finding }) {
  const [expanded, setExpanded] = useState(true);
  const data = (finding.data ?? {}) as Record<string, unknown>;
  const rec = (data.recommendation as string) ?? '';
  const recCfg = REC_CONFIG[rec] ?? REC_CONFIG['proceed_with_caution'];
  const keyFindings = (data.key_findings as string[]) ?? [];
  const riskAssessment = (data.risk_assessment as string) ?? '';
  const rationale = (data.rationale as string) ?? finding.description ?? '';
  const reportSections = (data.report_sections as number) ?? 0;

  return (
    <div className={`border ${recCfg.border} rounded-xl overflow-hidden`}>
      <button
        onClick={() => setExpanded((v) => !v)}
        className={`w-full flex items-start gap-3 px-5 py-4 text-left hover:bg-theme-border/20 transition-colors ${recCfg.bg}`}
      >
        <FileText className={`w-4 h-4 ${recCfg.color} flex-shrink-0 mt-0.5`} />
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold leading-snug">Executive Summary — GPT-4o Analysis</p>
          <p className="text-[10px] font-mono text-theme-text-muted mt-0.5">
            Generated by OpenAI GPT-4o · {reportSections} report sections
          </p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <span className={`text-[9px] font-mono font-semibold px-2 py-0.5 rounded border ${recCfg.bg} ${recCfg.border} ${recCfg.color}`}>
            {recCfg.label}
          </span>
          {expanded
            ? <ChevronDown className="w-3.5 h-3.5 text-theme-text-muted" />
            : <ChevronRight className="w-3.5 h-3.5 text-theme-text-muted" />
          }
        </div>
      </button>

      {expanded && (
        <div className="px-5 py-4 border-t border-theme-border bg-theme-bg/40 space-y-4">
          {riskAssessment && (
            <div>
              <p className="text-[10px] font-mono text-theme-text-muted uppercase tracking-wider mb-1">Risk Assessment</p>
              <p className="text-[11px] text-theme-text leading-relaxed">{riskAssessment}</p>
            </div>
          )}

          {keyFindings.length > 0 && (
            <div>
              <p className="text-[10px] font-mono text-theme-text-muted uppercase tracking-wider mb-2">Key Findings</p>
              <ul className="space-y-1.5">
                {keyFindings.map((f, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <TrendingUp className="w-3 h-3 text-theme-text-muted flex-shrink-0 mt-0.5" />
                    <span className="text-[11px] text-theme-text leading-relaxed">{f}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {rationale && (
            <div>
              <p className="text-[10px] font-mono text-theme-text-muted uppercase tracking-wider mb-1">Recommendation Rationale</p>
              <p className="text-[11px] text-theme-text leading-relaxed">{rationale}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function FindingCard({ finding }: { finding: Finding }) {
  const [expanded, setExpanded] = useState(false);
  const sev = (finding.severity as SevKey) in SEVERITY_CONFIG
    ? (finding.severity as SevKey)
    : 'info';
  const cfg = SEVERITY_CONFIG[sev];
  const Icon = cfg.icon;

  return (
    <div className={`border ${cfg.border} rounded-xl overflow-hidden`}>
      <button
        onClick={() => setExpanded((v) => !v)}
        className={`w-full flex items-start gap-3 px-4 py-3.5 text-left hover:bg-theme-border/20 transition-colors ${cfg.bg}`}
      >
        <Icon className={`w-4 h-4 ${cfg.color} flex-shrink-0 mt-0.5`} />
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold leading-snug">{finding.title}</p>
          {finding.source_system && (
            <p className="text-[10px] font-mono text-theme-text-muted mt-0.5">
              {finding.source_system.replace(/_/g, ' → ').toUpperCase()}
            </p>
          )}
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          {finding.requires_human_review && (
            <span className="hidden sm:inline text-[9px] font-mono px-1.5 py-0.5 rounded border border-amber-500/30 text-amber-400 bg-amber-500/10">
              REVIEW
            </span>
          )}
          {expanded
            ? <ChevronDown className="w-3.5 h-3.5 text-theme-text-muted" />
            : <ChevronRight className="w-3.5 h-3.5 text-theme-text-muted" />
          }
        </div>
      </button>

      {expanded && finding.description && (
        <div className="px-4 py-3 border-t border-theme-border bg-theme-bg/40 space-y-2">
          <p className="text-[11px] text-theme-text leading-relaxed">{finding.description}</p>
          <div className="flex flex-wrap gap-2 pt-1">
            <span className={`inline-flex items-center gap-1 text-[9px] font-mono px-2 py-0.5 rounded-full border ${cfg.badge}`}>
              <Icon className="w-2.5 h-2.5" /> {cfg.label}
            </span>
            <span className="text-[9px] font-mono px-2 py-0.5 rounded-full border border-theme-border text-theme-text-muted">
              {finding.finding_type.replace(/_/g, ' ').toUpperCase()}
            </span>
          </div>
        </div>
      )}
    </div>
  );
}

function SeverityGroup({
  severity,
  findings,
  defaultOpen = false,
}: {
  severity: SevKey;
  findings: Finding[];
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  if (findings.length === 0) return null;
  const cfg = SEVERITY_CONFIG[severity];
  const Icon = cfg.icon;

  return (
    <div className="border border-theme-border rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-5 py-3.5 bg-theme-bg/60 hover:bg-theme-border/30 transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <Icon className={`w-4 h-4 ${cfg.color}`} />
          <span className="text-xs font-semibold tracking-wide">{cfg.label}</span>
          <span className={`px-2 py-0.5 rounded-full border text-[10px] font-mono font-semibold ${cfg.badge}`}>
            {findings.length}
          </span>
        </div>
        {open
          ? <ChevronDown className="w-4 h-4 text-theme-text-muted" />
          : <ChevronRight className="w-4 h-4 text-theme-text-muted" />
        }
      </button>
      {open && (
        <div className="px-4 py-3 space-y-2 border-t border-theme-border bg-theme-bg/20">
          {findings.map((f) => (
            <FindingCard key={f.id} finding={f} />
          ))}
        </div>
      )}
    </div>
  );
}

export default function ResultsPanel({ engagement }: Props) {
  const [findings, setFindings] = useState<Finding[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showReviewOnly, setShowReviewOnly] = useState(false);

  const fetchFindings = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await findingsApi.list(engagement.id);
      setFindings(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load findings');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchFindings();
  }, [engagement.id]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-3">
        <Loader2 className="w-6 h-6 animate-spin text-theme-text-muted" />
        <p className="text-xs font-mono text-theme-text-muted">Loading findings…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-20 gap-3 text-center">
        <XCircle className="w-8 h-8 text-red-400" />
        <p className="text-sm font-semibold">Failed to load findings</p>
        <p className="text-xs text-theme-text-muted font-mono">{error}</p>
        <button
          onClick={fetchFindings}
          className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-mono border border-theme-border rounded-lg hover:bg-theme-border/30 transition-colors"
        >
          <RefreshCw className="w-3 h-3" /> Retry
        </button>
      </div>
    );
  }

  // Separate executive summary from regular findings
  const execSummaryFinding = findings.find((f) => f.finding_type === 'executive_summary');
  const regularFindings = findings.filter((f) => f.finding_type !== 'executive_summary');

  const visible = showReviewOnly ? regularFindings.filter((f) => f.requires_human_review) : regularFindings;
  const criticals = visible.filter((f) => f.severity === 'critical');
  const warnings  = visible.filter((f) => f.severity === 'warning');
  const infos     = visible.filter((f) => f.severity === 'info');
  const reviewCount = regularFindings.filter((f) => f.requires_human_review).length;

  return (
    <div className="space-y-4">
      {/* Summary bar */}
      <div className="border border-theme-border rounded-xl p-5">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <h3 className="text-sm font-semibold">{engagement.company_name} — Due Diligence Findings</h3>
            <p className="text-[11px] font-mono text-theme-text-muted mt-1">
              {engagement.completed_at
                ? `Completed ${new Date(engagement.completed_at).toLocaleString()}`
                : 'Completed'}
              {' · '}{regularFindings.length} findings
            </p>
          </div>

          {/* Severity summary pills */}
          <div className="flex items-center gap-2 flex-wrap">
            {criticals.length > 0 && (
              <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-mono font-semibold border bg-red-500/15 border-red-500/30 text-red-400">
                <XCircle className="w-3 h-3" /> {criticals.length} CRITICAL
              </span>
            )}
            {warnings.length > 0 && (
              <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-mono font-semibold border bg-amber-500/15 border-amber-500/30 text-amber-400">
                <AlertTriangle className="w-3 h-3" /> {warnings.length} WARNING
              </span>
            )}
            {infos.length > 0 && (
              <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-mono font-semibold border bg-blue-500/15 border-blue-500/30 text-blue-400">
                <Info className="w-3 h-3" /> {infos.length} INFO
              </span>
            )}
          </div>
        </div>

        {/* Filter + refresh + export row */}
        <div className="flex items-center gap-3 mt-4 pt-4 border-t border-theme-border">
          <button
            onClick={() => setShowReviewOnly((v) => !v)}
            className={`flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-mono rounded-lg border transition-colors ${
              showReviewOnly
                ? 'bg-amber-500/15 border-amber-500/40 text-amber-400'
                : 'border-theme-border text-theme-text-muted hover:text-theme-text hover:bg-theme-border/30'
            }`}
          >
            {showReviewOnly ? <Eye className="w-3 h-3" /> : <EyeOff className="w-3 h-3" />}
            NEEDS REVIEW ({reviewCount})
          </button>
          <button
            onClick={fetchFindings}
            className="flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-mono border border-theme-border rounded-lg text-theme-text-muted hover:text-theme-text hover:bg-theme-border/30 transition-colors"
          >
            <RefreshCw className="w-3 h-3" /> REFRESH
          </button>
          {/* Export buttons */}
          <div className="ml-auto flex items-center gap-2">
            <a
              href={`${BACKEND_URL}/api/v1/engagements/${engagement.id}/export/pdf`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-mono border
                         border-theme-border rounded-lg text-theme-text-muted
                         hover:text-theme-text hover:bg-theme-border/30 transition-colors"
              title="Download report as PDF"
            >
              <Download className="w-3 h-3" /> PDF
            </a>
            <a
              href={`${BACKEND_URL}/api/v1/engagements/${engagement.id}/export/excel`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-mono border
                         border-green-500/30 rounded-lg text-green-400/70
                         hover:text-green-400 hover:bg-green-500/10 transition-colors"
              title="Download financial model as Excel workbook"
            >
              <Download className="w-3 h-3" /> EXCEL
            </a>
          </div>
        </div>
      </div>

      {/* Executive Summary — pinned at top if present */}
      {execSummaryFinding && (
        <ExecutiveSummaryCard finding={execSummaryFinding} />
      )}

      {regularFindings.length === 0 ? (
        <div className="border border-dashed border-theme-border rounded-xl py-16 text-center space-y-2">
          <Info className="w-8 h-8 text-theme-text-muted mx-auto" />
          <p className="text-sm font-semibold">No findings recorded</p>
          <p className="text-xs text-theme-text-muted font-mono">
            The pipeline completed but produced no findings
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          <SeverityGroup severity="critical" findings={criticals} defaultOpen />
          <SeverityGroup severity="warning"  findings={warnings}  defaultOpen />
          <SeverityGroup severity="info"     findings={infos} />
        </div>
      )}
    </div>
  );
}
