"""
Slack distribution channel.

Posts a formatted due diligence summary to a Slack channel via Incoming Webhooks.

Configuration (from engagement config or environment):
  - slack_webhook_url   Slack Incoming Webhook URL
                        e.g. https://hooks.slack.com/services/T.../B.../xxx
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

import httpx

logger = logging.getLogger(__name__)


def _recommendation_emoji(recommendation: str) -> str:
    return {
        "proceed": ":white_check_mark:",
        "proceed_with_caution": ":warning:",
        "do_not_proceed": ":x:",
    }.get(recommendation, ":mag:")


def _severity_emoji(severity: str) -> str:
    return {"critical": ":red_circle:", "warning": ":yellow_circle:", "info": ":blue_circle:"}.get(
        severity.lower(), ":white_circle:"
    )


def _recommendation_label(recommendation: str) -> str:
    return {
        "proceed": "PROCEED",
        "proceed_with_caution": "PROCEED WITH CAUTION",
        "do_not_proceed": "DO NOT PROCEED",
    }.get(recommendation, recommendation.upper().replace("_", " "))


async def post_summary(
    webhook_url: str,
    deliverables: dict,
    findings: list[dict],
    target_company: str,
    pe_firm: str,
    report_url: str = "",
) -> dict:
    """
    Post a due diligence summary to a Slack channel via webhook.

    Args:
        webhook_url:    Slack Incoming Webhook URL.
        deliverables:   Full deliverables dict from delivery agent.
        findings:       List of finding dicts for the summary table.
        target_company: Name of the company being diligenced.
        pe_firm:        Name of the PE firm.
        report_url:     Optional URL to the full report / frontend.

    Returns:
        dict with status and any error details.
    """
    exec_summary = deliverables.get("executive_summary", {})
    recommendation = exec_summary.get("recommendation", "proceed_with_caution")
    rationale = exec_summary.get("recommendation_rationale", "")
    key_findings = exec_summary.get("key_findings", [])
    source_count = exec_summary.get("source_count", 0)

    rec_emoji = _recommendation_emoji(recommendation)
    rec_label = _recommendation_label(recommendation)
    date_str = datetime.now(timezone.utc).strftime("%b %d, %Y %H:%M UTC")

    # Count by severity
    severity_counts: dict[str, int] = {"critical": 0, "warning": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    # Build blocks payload
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"KEEN Due Diligence Report — {target_company}",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*PE Firm:*\n{pe_firm}"},
                {"type": "mrkdwn", "text": f"*Target:*\n{target_company}"},
                {"type": "mrkdwn", "text": f"*Date:*\n{date_str}"},
                {"type": "mrkdwn", "text": f"*Sources Analyzed:*\n{source_count}"},
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{rec_emoji} *Recommendation: {rec_label}*\n{rationale[:300] if rationale else ''}",
            },
        },
    ]

    # Severity summary
    sev_text = (
        f":red_circle: *{severity_counts['critical']} Critical*   "
        f":yellow_circle: *{severity_counts['warning']} Warning*   "
        f":blue_circle: *{severity_counts['info']} Info*"
    )
    blocks.append({
        "type": "section",
        "text": {"type": "mrkdwn", "text": f"*Findings:* {sev_text}"},
    })

    # Top key findings
    if key_findings:
        blocks.append({"type": "divider"})
        findings_text = "\n".join(f"• {f}" for f in key_findings[:5])
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Key Findings:*\n{findings_text}",
            },
        })

    # Optional: link to report
    if report_url:
        blocks.append({
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View Full Report"},
                    "url": report_url,
                    "style": "primary",
                }
            ],
        })

    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "_CONFIDENTIAL — For authorized recipients only. Generated by KEEN._",
            }
        ],
    })

    payload = {"blocks": blocks}

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(webhook_url, json=payload)
            if response.status_code == 200 and response.text == "ok":
                logger.info("Slack: posted summary for %s", target_company)
                return {"status": "sent", "channel": "slack"}
            else:
                logger.warning(
                    "Slack: unexpected response %d — %s", response.status_code, response.text
                )
                return {
                    "status": "error",
                    "channel": "slack",
                    "error": f"HTTP {response.status_code}: {response.text}",
                }
    except Exception as exc:
        logger.exception("Slack distribution failed: %s", exc)
        return {"status": "error", "channel": "slack", "error": str(exc)}
